from __future__ import annotations

import base64
import binascii
import json
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb


SCHEMA = """
CREATE TABLE IF NOT EXISTS device_state (
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (vendor, product)
);

CREATE TABLE IF NOT EXISTS dives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    fingerprint_hex TEXT,
    dive_uid TEXT NOT NULL UNIQUE,
    started_at TEXT,
    duration_seconds INTEGER,
    max_depth_m DOUBLE PRECISION,
    avg_depth_m DOUBLE PRECISION,
    fields_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_sha256 TEXT NOT NULL,
    raw_data BYTEA NOT NULL,
    samples_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    imported_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dives_started_at ON dives (started_at DESC, id DESC);
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def init_db(conn: psycopg.Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(SCHEMA)
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS fields_json JSONB NOT NULL DEFAULT '{}'::jsonb")
        cur.execute("ALTER TABLE dives ADD COLUMN IF NOT EXISTS samples_json JSONB NOT NULL DEFAULT '[]'::jsonb")
    conn.commit()


def open_db(database_url: str) -> psycopg.Connection:
    conn = psycopg.connect(database_url, row_factory=dict_row)
    init_db(conn)
    return conn


def decode_dive_row(row: dict, include_samples: bool, include_raw_data: bool) -> dict:
    fields = row.get("fields_json") or {}
    samples = row.get("samples_json") or []
    raw_data = row.get("raw_data")

    payload = {
        "id": row["id"],
        "vendor": row["vendor"],
        "product": row["product"],
        "fingerprint_hex": row.get("fingerprint_hex"),
        "dive_uid": row["dive_uid"],
        "started_at": row.get("started_at"),
        "duration_seconds": row.get("duration_seconds"),
        "max_depth_m": row.get("max_depth_m"),
        "avg_depth_m": row.get("avg_depth_m"),
        "fields": fields if isinstance(fields, dict) else json.loads(fields),
        "raw_sha256": row["raw_sha256"],
        "raw_data_size": len(raw_data) if raw_data is not None else 0,
        "imported_at": row["imported_at"],
    }

    if isinstance(samples, str):
        samples = json.loads(samples)
    payload["sample_count"] = len(samples)
    if include_samples:
        payload["samples"] = samples
    if include_raw_data and raw_data is not None:
        payload["raw_data_b64"] = base64.b64encode(raw_data).decode("ascii")
    return payload


def insert_dive_record(conn: psycopg.Connection, payload: dict) -> bool:
    imported_at = payload.get("imported_at") or now_iso()
    fields = payload.get("fields") or {}
    samples = payload.get("samples") or []
    raw_data = decode_base64_payload(payload)

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO dives(
                vendor, product, fingerprint_hex, dive_uid, started_at,
                duration_seconds, max_depth_m, avg_depth_m, fields_json,
                raw_sha256, raw_data, samples_json, imported_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (dive_uid) DO NOTHING
            RETURNING id
            """,
            (
                payload["vendor"],
                payload["product"],
                payload.get("fingerprint_hex"),
                payload["dive_uid"],
                payload.get("started_at"),
                payload.get("duration_seconds"),
                payload.get("max_depth_m"),
                payload.get("avg_depth_m"),
                Jsonb(fields),
                payload["raw_sha256"],
                raw_data,
                Jsonb(samples),
                imported_at,
            ),
        )
        inserted = cur.fetchone() is not None
    conn.commit()
    return inserted


def get_dive_id_by_uid(conn: psycopg.Connection, dive_uid: str) -> int | None:
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM dives WHERE dive_uid=%s", (dive_uid,))
        row = cur.fetchone()
    return row["id"] if row else None


def save_device_state(conn: psycopg.Connection, vendor: str, product: str, fingerprint_hex: str | None) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO device_state(vendor, product, fingerprint_hex, updated_at)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (vendor, product)
            DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
            """,
            (vendor, product, fingerprint_hex, now_iso()),
        )
    conn.commit()


def get_device_state(conn: psycopg.Connection, vendor: str, product: str) -> dict:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT vendor, product, fingerprint_hex, updated_at
            FROM device_state
            WHERE vendor=%s AND product=%s
            """,
            (vendor, product),
        )
        row = cur.fetchone()
    if not row:
        return {
            "vendor": vendor,
            "product": product,
            "fingerprint_hex": None,
            "updated_at": None,
        }
    return row


def list_dives(
    conn: psycopg.Connection,
    include_samples: bool,
    include_raw_data: bool,
    limit: int,
    offset: int,
) -> tuple[list[dict], int]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT *
            FROM dives
            ORDER BY started_at DESC, id DESC
            LIMIT %s OFFSET %s
            """,
            (limit, offset),
        )
        rows = cur.fetchall()
        cur.execute("SELECT COUNT(*) AS total FROM dives")
        total = cur.fetchone()["total"]
    dives = [decode_dive_row(row, include_samples, include_raw_data) for row in rows]
    return dives, total


def get_dive(conn: psycopg.Connection, dive_id: int, include_raw_data: bool) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE id=%s", (dive_id,))
        row = cur.fetchone()
    return decode_dive_row(row, include_samples=True, include_raw_data=include_raw_data) if row else None


def sanitize_logbook_payload(payload: dict | None) -> dict:
    source = payload or {}
    if isinstance(source.get("logbook"), dict):
        source = source["logbook"]
    commit = bool((payload or {}).get("commit"))

    def clean_text(key: str) -> str:
        value = source.get(key, "")
        return value.strip() if isinstance(value, str) else ""

    logbook = {
        "site": clean_text("site"),
        "buddy": clean_text("buddy"),
        "guide": clean_text("guide"),
        "notes": clean_text("notes"),
        "updated_at": now_iso(),
    }

    required = ("site", "buddy", "guide")
    if commit and all(logbook[key] for key in required):
        logbook["status"] = "complete"
        existing_completed_at = source.get("completed_at")
        logbook["completed_at"] = existing_completed_at if isinstance(existing_completed_at, str) and existing_completed_at else now_iso()
    else:
        logbook["status"] = "pending"

    return logbook


def update_dive_logbook(conn: psycopg.Connection, dive_id: int, payload: dict | None) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM dives WHERE id=%s", (dive_id,))
        row = cur.fetchone()
        if not row:
            return None

        fields = row.get("fields_json") or {}
        if not isinstance(fields, dict):
            fields = json.loads(fields)
        fields["logbook"] = sanitize_logbook_payload(payload)

        cur.execute(
            "UPDATE dives SET fields_json=%s WHERE id=%s",
            (Jsonb(fields), dive_id),
        )
    conn.commit()
    return get_dive(conn, dive_id, include_raw_data=False)


def import_sqlite_device_state(conn: psycopg.Connection, rows: list[dict]) -> int:
    if not rows:
        return 0
    with conn.cursor() as cur:
        for row in rows:
            cur.execute(
                """
                INSERT INTO device_state(vendor, product, fingerprint_hex, updated_at)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (vendor, product)
                DO UPDATE SET fingerprint_hex=excluded.fingerprint_hex, updated_at=excluded.updated_at
                """,
                (row["vendor"], row["product"], row["fingerprint_hex"], row["updated_at"]),
            )
    conn.commit()
    return len(rows)


def import_sqlite_dive_rows(conn: psycopg.Connection, rows: list[dict]) -> int:
    if not rows:
        return 0
    inserted = 0
    with conn.cursor() as cur:
        for row in rows:
            fields = row["fields_json"]
            samples = row["samples_json"]
            if isinstance(fields, str):
                fields = json.loads(fields)
            if isinstance(samples, str):
                samples = json.loads(samples)

            cur.execute(
                """
                INSERT INTO dives(
                    id, vendor, product, fingerprint_hex, dive_uid, started_at,
                    duration_seconds, max_depth_m, avg_depth_m, fields_json,
                    raw_sha256, raw_data, samples_json, imported_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (dive_uid) DO NOTHING
                RETURNING id
                """,
                (
                    row["id"],
                    row["vendor"],
                    row["product"],
                    row["fingerprint_hex"],
                    row["dive_uid"],
                    row["started_at"],
                    row["duration_seconds"],
                    row["max_depth_m"],
                    row["avg_depth_m"],
                    Jsonb(fields),
                    row["raw_sha256"],
                    row["raw_data"],
                    Jsonb(samples),
                    row["imported_at"],
                ),
            )
            if cur.fetchone() is not None:
                inserted += 1

        cur.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('dives', 'id'),
                COALESCE((SELECT MAX(id) FROM dives), 1),
                true
            )
            """
        )
    conn.commit()
    return inserted


def decode_base64_payload(payload: dict) -> bytes:
    try:
        return base64.b64decode(payload["raw_data_b64"], validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ValueError("raw_data_b64 must be valid base64") from exc
