//go:build windows && bundled

package divecomputer

import (
	"embed"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/jLemmings/DiveVault-Importer/internal/nativeruntime"
)

// Generated by scripts/package before compiling with -tags bundled.
//
//go:embed runtime/*.dll
var nativeLibraries embed.FS

// Release builds search only the extracted bundle and Windows system directory.
const runtimeLoadFlags = 0x100 | 0x800 // DLL_LOAD_DIR | SYSTEM32

func runtimePath() (string, error) {
	cache, err := os.UserCacheDir()
	if err != nil {
		return "", err
	}
	files, err := fs.Sub(nativeLibraries, "runtime")
	if err != nil {
		return "", err
	}
	return nativeruntime.Extract(files, filepath.Join(cache, "DiveVault Importer", "runtime"))
}
